parameters:
    database_driver:   ~
    database_host:     ~
    database_port:     ~
    database_name:     ~
    database_user:     ~
    database_password: ~

    mailer_transport: gmail
    mailer_encryption: ssl
    mailer_auth_mode: login
    mailer_host: smtp.gmail.com
    mailer_user: astill@ulusnow.co.uk
    mailer_password: Football123

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
