parameters:
    database_driver:   pdo_mysql
    database_host:     mysymbloginstance.czpsqqrwfrir.us-west-2.rds.amazonaws.com
    database_port:     3306
    database_name:     symfony
    database_user:     albertstill
    database_password: football123

    mailer_transport: gmail
    mailer_encryption: ssl
    mailer_auth_mode: login
    mailer_host: smtp.gmail.com
    mailer_user: astill@ulusnow.co.uk
    mailer_password: Football123

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
